name: Update Euribor Rates

on:
  schedule:
    # Run every day at 10:00 UTC
    - cron: "0 10 * * *"
  workflow_dispatch: # Allow manual trigger

# Define permissions explicitly for the GITHUB_TOKEN
permissions:
  contents: write # Needed to push to the repository

jobs:
  update-euribor-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .

      - name: Update Euribor rates
        run: |
          python -m src.euribor

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit and push changes
        run: |
          git add api/
          git diff --staged --quiet || (git commit -m "Update Euribor rates ($(date '+%Y-%m-%d %H:%M:%S %Z')) [skip ci]" && git push)
